-- Define base color aliases
vim.api.nvim_set_hl(0, "Black",   { link = "Normal" })
vim.api.nvim_set_hl(0, "Gray",    { link = "Comment" })
vim.api.nvim_set_hl(0, "Cyan",    { link = "Constant" })
vim.api.nvim_set_hl(0, "Blue",    { link = "Identifier" })
vim.api.nvim_set_hl(0, "Green",   { link = "Statement" })
vim.api.nvim_set_hl(0, "Orange",  { link = "PreProc" })
vim.api.nvim_set_hl(0, "Yellow",  { link = "Type" })
vim.api.nvim_set_hl(0, "Red",     { link = "Special" })
vim.api.nvim_set_hl(0, "Violet",  { link = "Underlined" })
vim.api.nvim_set_hl(0, "Magenta", { link = "helpNote" })

-- LSP semantic token highlights (link to base colors)
vim.api.nvim_set_hl(0, "@lsp.type.namespace",      { link = "Cyan" })
vim.api.nvim_set_hl(0, "@lsp.type.type",           { link = "Red" })
vim.api.nvim_set_hl(0, "@lsp.type.class",          { link = "Red" })
vim.api.nvim_set_hl(0, "@lsp.type.enum",           { link = "Yellow" })
vim.api.nvim_set_hl(0, "@lsp.type.interface",      { link = "Red" })
vim.api.nvim_set_hl(0, "@lsp.type.struct",         { link = "Green" })
vim.api.nvim_set_hl(0, "@lsp.type.typeParameter",  { link = "Red" })
vim.api.nvim_set_hl(0, "@lsp.type.parameter",      { link = "Yellow" })
vim.api.nvim_set_hl(0, "@lsp.type.variable",       { link = "Black" })
vim.api.nvim_set_hl(0, "@lsp.type.property",       { link = "Yellow" })
vim.api.nvim_set_hl(0, "@lsp.type.enumMember",     { link = "Orange" })
vim.api.nvim_set_hl(0, "@lsp.type.event",          { link = "Violet" })
vim.api.nvim_set_hl(0, "@lsp.type.function",       { link = "Blue" })
vim.api.nvim_set_hl(0, "@lsp.type.method",         { link = "Violet" })
vim.api.nvim_set_hl(0, "@lsp.type.macro",          { link = "Orange" })
vim.api.nvim_set_hl(0, "@lsp.type.keyword",        { link = "Green" })
vim.api.nvim_set_hl(0, "@lsp.type.modifier",       { link = "Yellow" })
vim.api.nvim_set_hl(0, "@lsp.type.comment",        { link = "Gray" })
vim.api.nvim_set_hl(0, "@lsp.type.string",         { link = "Green" })
vim.api.nvim_set_hl(0, "@lsp.type.number",         { link = "Yellow" })
vim.api.nvim_set_hl(0, "@lsp.type.regexp",         { link = "Green" })
vim.api.nvim_set_hl(0, "@lsp.type.operator",       { link = "Violet" })
vim.api.nvim_set_hl(0, "@lsp.type.decorator",      { link = "Violet" })
